### ISSUE TITLE
Java function doesn't receive request from faas-flow

### ISSUE THREAD

**Issue by tim-hellhake** [s8sg/faas-flow#65] opened 2019-07-23 12:14 UTC
The `SYNC Chain` example calls two functions but returns only the result of the second function.
How can I pipe the result of the first function into the second function?

**Comment by s8sg** [comment] 2019-07-23 14:01
hi @tim-hellhake, 
For `sync chain` the call pattern is 
```go
flow.SyncNode().Apply("func1").Apply("func2")
```
In this above case `func1` output gets piped to `func2` 
Can you refer which example are you following ?

**Comment by s8sg** [comment] 2019-07-23 14:23
Another example sync chain with image filter [here](https://github.com/s8sg/image-filter-flow)
and also check if the gateway in env is right 
```yml
gateway: "gateway:8080"
```

**Comment by tim-hellhake** [comment] 2019-07-23 18:16
I have a simple java handler which prepends the current date:

```
    public IResponse Handle(IRequest req) {
        Response res = new Response();
        res.setBody(new Date() + ": " + req.getBody());

        return res;
    }
```

I tried to apply the function twice:

```
flow.SyncNode().Apply("date").Apply("date")
```

If i call the flow with the body `foo` i get `Tue Jul 23 18:15:22 GMT 2019: ` as result.
I would expect something like `Tue Jul 23 18:15:22 GMT 2019: Tue Jul 23 18:15:22 GMT 2019: foo`.

**Comment by tim-hellhake** [comment] 2019-07-23 18:17
The java handler works as expected:
`foo` -> `Tue Jul 23 18:17:04 GMT 2019: foo`

**Comment by s8sg** [comment] 2019-07-24 01:50
I setup a dummy implementation to check the issue 
https://github.com/s8sg/java-test-flow

It seems the issue is only with `java8` function, where `python`, `node` works fine 
I'll take a look in details soon. Great if you can help to debug

**Comment by s8sg** [comment] 2019-07-24 05:00
@tim-hellhake This was happening as we were keeping the connection open for each function call. This PR fixes it. Can you please check if possible

**Comment by s8sg** [comment] 2019-07-24 06:10
@chennqqi can you check this. Function with `java8` as template doesn't receive the data from faas-flow. Although this function works fine: https://github.com/s8sg/java-test-flow/blob/master/test-java/handler.go

We had some issue with connection being open, but that doesn't fix it either.

**Comment by s8sg** [comment] 2019-07-27 13:43
@tim-hellhake The issue was quite silly . The method `POST` was not being set. The PR fixes it. I'll merge and close the issue. Please give it another try, it should work.

**Closed** 2019-07-27 13:44 UTC
Labels: bug, help wanted

**Comment by tim-hellhake** [comment] 2019-07-27 14:34
I updated my flow function with:
1. ```faas template pull --overwrite https://github.com/s8sg/faas-flow```
2. ```faas-cli up -f flow.yml```
Now I get a 500 when I call the function.
I looked into the flow functions logs and found this:
```
2019/07/27 14:28:12 stderr: 2019/07/27 14:28:12 http: panic serving 127.0.0.1:39422: [Request `bku5uv64pd7q5nmpgj40`] Failed, Node(0_1_sync), Function(java-append-date), error: function execution failed, Post http://gateway:8080/function/java-append-date: dial tcp: lookup gateway on
2019/07/27 14:28:12 stderr: 10.100.0.10:53: no such host
```

I assume this is caused by https://github.com/s8sg/faas-flow/pull/67?

**Comment by s8sg** [comment] 2019-07-27 14:41
If you using Kubernets can you please try with ‘gateway.openfaas:8080’. Ideally the call to OpenFaaS function must be made via gateway.

**Comment by tim-hellhake** [comment] 2019-07-27 14:52
Yeah that's what I just tried 😬
I created an issue: https://github.com/s8sg/faas-flow/issues/77
With the namespace added java functions finally work.

**Comment by s8sg** [comment] 2019-07-27 15:00
We expect user to set the gateway based on the deployment environment. This is documented in README. 

https://github.com/s8sg/faas-flow/blob/master/README.md#add-configuration
